##
## Makefile for Makefile in /home/lokoum/prog/dante/generateur
## 
## Made by Lucas Troncy
## Login   <troncy_l@epitech.net>
## 
## Started on  Sat Apr 30 17:19:45 2016 Lucas Troncy
## Last update Sat Apr 30 17:26:25 2016 Lucas Troncy
##

SRCS	=	src/main.c

OBJS	=	$(SRCS:.c=.o)

NAME	=	generateur

CFLAGS	=	-Wall -ansi -pedantic -Werror

$(NAME):	$(OBJS)
		gcc -o $(NAME) $(OBJS)
